
services:
  db:
    container_name: postgres_db
    image: postgres
    environment:
      POSTGRES_USER: hr_user
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres_db
    volumes:
      - db:/data/postgres_db
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:



